const STORAGE_KEY='aesost-membership-admin-demo-v1';
const plans=[
  {id:'basic',name:'Basic Plan',price:49000,benefits:['월 2회 이용','멤버 전용 뉴스레터','기본 예약 혜택']},
  {id:'plus',name:'Plus Plan',price:89000,benefits:['월 4회 이용','우선 예약','멤버 이벤트 초대']},
  {id:'studio',name:'Studio Plan',price:149000,benefits:['월 8회 이용','게스트 패스 2회','전용 프로그램 우선권']}
];
const seed={members:[
  {id:'m1',name:'김서윤',email:'seoyun@example.com',plan:'studio',start:'2026-06-28',end:'2026-09-28',credits:3,status:'Expiring',payment:'Paid',nextBilling:'2026-09-28'},
  {id:'m2',name:'박도현',email:'dohyun@example.com',plan:'plus',start:'2026-07-12',end:'2026-10-12',credits:2,status:'Active',payment:'Paid',nextBilling:'2026-10-12'},
  {id:'m3',name:'이유진',email:'yujin@example.com',plan:'studio',start:'2026-06-18',end:'2026-09-18',credits:5,status:'Expiring',payment:'Pending',nextBilling:'2026-09-18'},
  {id:'m4',name:'정하린',email:'harin@example.com',plan:'basic',start:'2026-08-02',end:'2026-11-02',credits:1,status:'Active',payment:'Paid',nextBilling:'2026-10-02'},
  {id:'m5',name:'한민재',email:'minjae@example.com',plan:'plus',start:'2026-07-25',end:'2026-10-25',credits:4,status:'Paused',payment:'Pending',nextBilling:'2026-09-25'},
  {id:'m6',name:'윤지우',email:'jiwoo@example.com',plan:'basic',start:'2026-08-20',end:'2026-11-20',credits:2,status:'Active',payment:'Paid',nextBilling:'2026-09-20'}
],activity:[
  {id:'a1',date:'2026-09-06',title:'김서윤 멤버십 만료 임박',detail:'Studio Plan · 9월 28일 만료',type:'RENEWAL'},
  {id:'a2',date:'2026-09-05',title:'이유진 결제 확인 필요',detail:'Studio Plan · ₩149,000 미결제',type:'BILLING'},
  {id:'a3',date:'2026-09-04',title:'윤지우 회원 등록',detail:'Basic Plan 신규 가입',type:'MEMBER'}
]};
let state=loadState();let currentFilter='all';let searchQuery='';
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||cloneSeed()}catch{return cloneSeed()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function planById(id){return plans.find(p=>p.id===id)}
function won(v){return '₩'+Number(v||0).toLocaleString('ko-KR')}
function esc(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function uid(prefix){return prefix+Date.now().toString(36)}
function addDays(date,days){const d=new Date(date+'T00:00:00');d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function toast(message){const el=document.querySelector('[data-toast]');el.textContent=message;el.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('is-visible'),1800)}
function log(title,detail,type='MEMBER'){state.activity.unshift({id:uid('a'),date:new Date().toISOString().slice(0,10),title,detail,type});state.activity=state.activity.slice(0,30)}
function setView(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('is-active',b.dataset.view===name));document.querySelectorAll('[data-view-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.viewPanel===name));const titles={dashboard:'회원 운영 현황',members:'회원 데이터베이스',plans:'멤버십 플랜',billing:'결제 현황',activity:'회원 활동 이력'};document.querySelector('[data-view-title]').textContent=titles[name]||'Membership Admin'}
document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.view)));document.querySelectorAll('[data-go]').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.go)));
function renderAll(){renderCounts();renderMetrics();renderDashboardMembers();renderPlanMix();renderRenewals();renderMembers();renderPlans();renderBilling();renderActivity();renderPlanSelect()}
function renderCounts(){document.querySelectorAll('[data-count="members"]').forEach(e=>e.textContent=state.members.length);document.querySelectorAll('[data-count="pending"]').forEach(e=>e.textContent=state.members.filter(m=>m.payment==='Pending').length)}
function renderMetrics(){const active=state.members.filter(m=>m.status==='Active'||m.status==='Expiring').length;const expiring=state.members.filter(m=>m.status==='Expiring').length;const pending=state.members.filter(m=>m.payment==='Pending').length;const revenue=state.members.filter(m=>m.payment==='Paid'&&m.status!=='Cancelled').reduce((s,m)=>s+(planById(m.plan)?.price||0),0);document.querySelector('[data-metric="active"]').textContent=active;document.querySelector('[data-metric="expiring"]').textContent=expiring;document.querySelector('[data-metric="pending"]').textContent=pending;document.querySelector('[data-metric="revenue"]').textContent=won(revenue)}
function renderDashboardMembers(){const target=document.querySelector('[data-dashboard-members]');target.innerHTML=state.members.slice(0,5).map(m=>`<div class="member-row"><div><strong>${esc(m.name)}</strong><small>${esc(m.email)}</small></div><span>${esc(planById(m.plan)?.name||'-')}</span><span>${m.end}</span><span class="status ${m.status}">${m.status}</span></div>`).join('')}
function renderPlanMix(){const target=document.querySelector('[data-plan-mix]');const total=Math.max(state.members.length,1);target.innerHTML=plans.map(p=>{const count=state.members.filter(m=>m.plan===p.id&&m.status!=='Cancelled').length;const pct=Math.round(count/total*100);return `<div class="plan-line"><span>${esc(p.name)}</span><b>${count}명</b><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join('')}
function renderRenewals(){const rows=state.members.filter(m=>m.status==='Expiring'||m.payment==='Pending').slice(0,4);document.querySelector('[data-renewals]').innerHTML=rows.map(m=>`<div class="renewal-item"><div><strong>${esc(m.name)}</strong><small>${esc(planById(m.plan)?.name||'-')} · ${m.end}</small></div><span class="status ${m.payment==='Pending'?'Pending':'Expiring'}">${m.payment==='Pending'?'Payment':'Renew'}</span></div>`).join('')||'<p>확인할 회원이 없습니다.</p>'}
function filteredMembers(){const q=searchQuery.toLowerCase();return state.members.filter(m=>(currentFilter==='all'||m.status===currentFilter)&&(!q||[m.name,m.email,planById(m.plan)?.name||''].some(v=>v.toLowerCase().includes(q))))}
function renderMembers(){const tbody=document.querySelector('[data-members-table]');tbody.innerHTML=filteredMembers().map(m=>`<tr><td><div class="member-name"><strong>${esc(m.name)}</strong><span>${esc(m.email)}</span></div></td><td>${esc(planById(m.plan)?.name||'-')}</td><td>${m.start}<br><small>${m.end}</small></td><td>${m.credits}</td><td><button class="mini-button" data-payment="${m.id}"><span class="status ${m.payment}">${m.payment}</span></button></td><td><button class="mini-button" data-status="${m.id}"><span class="status ${m.status}">${m.status}</span></button></td><td><div class="actions"><button class="mini-button" data-renew="${m.id}">갱신</button><button class="mini-button" data-plan-cycle="${m.id}">플랜 변경</button></div></td></tr>`).join('')||'<tr><td colspan="7">검색 결과가 없습니다.</td></tr>';tbody.querySelectorAll('[data-renew]').forEach(b=>b.addEventListener('click',()=>renewMember(b.dataset.renew)));tbody.querySelectorAll('[data-plan-cycle]').forEach(b=>b.addEventListener('click',()=>cyclePlan(b.dataset.planCycle)));tbody.querySelectorAll('[data-payment]').forEach(b=>b.addEventListener('click',()=>togglePayment(b.dataset.payment)));tbody.querySelectorAll('[data-status]').forEach(b=>b.addEventListener('click',()=>cycleMemberStatus(b.dataset.status)))}
function renderPlans(){document.querySelector('[data-plans-grid]').innerHTML=plans.map(p=>{const count=state.members.filter(m=>m.plan===p.id&&m.status!=='Cancelled').length;return `<article class="plan-card"><h3>${esc(p.name)}</h3><span class="price">${won(p.price)} <small>/ month</small></span><p>회원 운영을 위한 데모 멤버십 플랜</p><div class="benefits">${p.benefits.map(x=>`<span>✓ ${esc(x)}</span>`).join('')}</div><footer><span>${count} members</span><span>${Math.round(count/Math.max(state.members.length,1)*100)}%</span></footer></article>`}).join('')}
function renderBilling(){const paid=state.members.filter(m=>m.payment==='Paid'&&m.status!=='Cancelled').reduce((s,m)=>s+(planById(m.plan)?.price||0),0);const pending=state.members.filter(m=>m.payment==='Pending'&&m.status!=='Cancelled').reduce((s,m)=>s+(planById(m.plan)?.price||0),0);document.querySelector('[data-paid-total]').textContent=won(paid);document.querySelector('[data-pending-total]').textContent=won(pending);document.querySelector('[data-billing-count]').textContent=state.members.filter(m=>m.status!=='Cancelled').length;document.querySelector('[data-billing-table]').innerHTML=state.members.filter(m=>m.status!=='Cancelled').map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(planById(m.plan)?.name||'-')}</td><td>${won(planById(m.plan)?.price||0)}</td><td>${m.nextBilling}</td><td><span class="status ${m.payment}">${m.payment}</span></td><td><button class="mini-button" data-bill-toggle="${m.id}">${m.payment==='Paid'?'미결제로 변경':'결제 완료'}</button></td></tr>`).join('');document.querySelectorAll('[data-bill-toggle]').forEach(b=>b.addEventListener('click',()=>togglePayment(b.dataset.billToggle)))}
function renderActivity(){document.querySelector('[data-activity-list]').innerHTML=state.activity.map(a=>`<div class="activity-row"><time>${a.date}</time><div><strong>${esc(a.title)}</strong><small>${esc(a.detail)}</small></div><span>${esc(a.type)}</span></div>`).join('')}
function renderPlanSelect(){const s=document.querySelector('[data-plan-select]');s.innerHTML=plans.map(p=>`<option value="${p.id}">${p.name} · ${won(p.price)}</option>`).join('')}
function renewMember(id){const m=state.members.find(x=>x.id===id);if(!m)return;m.end=addDays(m.end,90);m.nextBilling=addDays(m.nextBilling,30);m.status='Active';m.payment='Paid';log(`${m.name} 멤버십 갱신`,`${planById(m.plan)?.name} · ${m.end}까지 연장`,'RENEWAL');saveState();renderAll();toast('멤버십을 갱신했습니다.')}
function cyclePlan(id){const m=state.members.find(x=>x.id===id);if(!m)return;const idx=plans.findIndex(p=>p.id===m.plan);m.plan=plans[(idx+1)%plans.length].id;log(`${m.name} 플랜 변경`,`${planById(m.plan)?.name}으로 변경`,'PLAN');saveState();renderAll();toast('플랜을 변경했습니다.')}
function togglePayment(id){const m=state.members.find(x=>x.id===id);if(!m)return;m.payment=m.payment==='Paid'?'Pending':'Paid';log(`${m.name} 결제 상태 변경`,`${m.payment} 상태로 변경`,'BILLING');saveState();renderAll();toast(`결제 상태: ${m.payment}`)}
function cycleMemberStatus(id){const m=state.members.find(x=>x.id===id);if(!m)return;const order=['Active','Expiring','Paused','Cancelled'];m.status=order[(order.indexOf(m.status)+1)%order.length];log(`${m.name} 회원 상태 변경`,`${m.status} 상태로 변경`,'MEMBER');saveState();renderAll();toast(`회원 상태: ${m.status}`)}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{currentFilter=btn.dataset.filter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('is-active',b===btn));renderMembers()}));document.querySelector('[data-search]').addEventListener('input',e=>{searchQuery=e.target.value.trim();renderMembers()});
function openModal(){const m=document.querySelector('[data-modal="member"]');m.classList.add('is-open');m.setAttribute('aria-hidden','false');m.querySelector('input')?.focus()}function closeModal(){const m=document.querySelector('[data-modal="member"]');m.classList.remove('is-open');m.setAttribute('aria-hidden','true')}
document.querySelector('[data-open-member]').addEventListener('click',openModal);document.querySelector('[data-close]').addEventListener('click',closeModal);document.querySelector('[data-modal="member"]').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelector('[data-member-form]').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const today=new Date().toISOString().slice(0,10);state.members.unshift({id:uid('m'),name:fd.get('name').trim(),email:fd.get('email').trim(),plan:fd.get('plan'),start:today,end:fd.get('end'),credits:Number(fd.get('credits')),status:'Active',payment:'Paid',nextBilling:addDays(today,30)});log(`${fd.get('name').trim()} 회원 등록`,`${planById(fd.get('plan'))?.name} 신규 가입`,'MEMBER');saveState();e.currentTarget.reset();closeModal();renderAll();setView('members');toast('회원을 등록했습니다.')});
document.querySelector('[data-reset]').addEventListener('click',()=>{if(!confirm('Membership Admin 데모 데이터를 초기화할까요?'))return;state=cloneSeed();saveState();renderAll();toast('데모 데이터를 초기화했습니다.')});
const params=new URLSearchParams(location.search);if(params.get('guide')==='1')document.body.classList.add('guide-mode');setView(params.get('view')||'dashboard');renderAll();
