const STORAGE_KEY='aesost-quote-flow-demo-v1';
const seed={quotes:[
{uid:'q1',series:'QT-26018',client:'오브젝트랩',contact:'김민지',title:'Corporate Website Renewal',version:3,valid:'2026-09-20',created:'2026-09-05',status:'Viewed',items:[{name:'Corporate Website Design',qty:1,unit:5500000},{name:'CMS & Admin Development',qty:1,unit:2500000}]},
{uid:'q2',series:'QT-26017',client:'모리리빙',contact:'정우성',title:'Brand Renewal Package',version:2,valid:'2026-09-18',created:'2026-09-04',status:'Approved',items:[{name:'Brand Identity Renewal',qty:1,unit:3500000},{name:'Brand Guideline',qty:1,unit:1500000}]},
{uid:'q3',series:'QT-26016',client:'아크헬스',contact:'강현우',title:'Admin System Development',version:1,valid:'2026-09-15',created:'2026-09-03',status:'Sent',items:[{name:'Admin Dashboard',qty:1,unit:7000000},{name:'Client Management Module',qty:1,unit:4000000}]},
{uid:'q4',series:'QT-26015',client:'스튜디오 모어',contact:'최유나',title:'Campaign Landing Page',version:1,valid:'2026-09-12',created:'2026-09-02',status:'Draft',items:[{name:'Landing Page Design',qty:1,unit:1800000},{name:'Responsive Development',qty:1,unit:1200000}]},
{uid:'q5',series:'QT-26014',client:'브릭앤코',contact:'윤세아',title:'B2B Inquiry System',version:2,valid:'2026-09-10',created:'2026-09-01',status:'Declined',items:[{name:'Inquiry Dashboard',qty:1,unit:4500000},{name:'Sales Pipeline Module',qty:1,unit:3000000}]}
]};
let state=loadState();
let searchQuery='';
let currentFilter='all';
let builder={uid:null,client:'',title:'',valid:'2026-09-30',version:1,items:[{name:'Website Planning & Design',qty:1,unit:2500000},{name:'Responsive Development',qty:1,unit:1800000}]};
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||cloneSeed()}catch{return cloneSeed()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function esc(value=''){return String(value).replace(/[&<>'\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[m]))}
function money(v){return new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(Math.round(Number(v)||0))}
function subtotal(q){return (q.items||[]).reduce((s,i)=>s+(Number(i.qty)||0)*(Number(i.unit)||0),0)}
function total(q){const sub=subtotal(q);return Math.round(sub*1.1)}
function toast(message){const el=document.querySelector('[data-toast]');if(!el)return;el.textContent=message;el.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('is-visible'),1800)}
function statusClass(v){return v.replaceAll(' ','-')}
function setView(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('is-active',b.dataset.view===name));document.querySelectorAll('[data-view-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.viewPanel===name));const titles={dashboard:'견적 운영 현황',quotes:'견적 데이터베이스',builder:'견적 빌더',versions:'견적 버전 관리',approval:'고객 승인 현황'};document.querySelector('[data-view-title]').textContent=titles[name]||'QuoteFlow'}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));
function visibleQuotes(){const q=searchQuery.toLowerCase();return state.quotes.filter(x=>(currentFilter==='all'||x.status===currentFilter)&&(!q||[x.series,x.client,x.contact,x.title,x.status].some(v=>String(v).toLowerCase().includes(q))))}
function renderAll(){renderCounts();renderMetrics();renderDashboard();renderQuotes();renderVersions();renderApproval();renderBuilder()}
function renderCounts(){document.querySelectorAll('[data-count="quotes"]').forEach(el=>el.textContent=state.quotes.length);document.querySelectorAll('[data-count="approval"]').forEach(el=>el.textContent=state.quotes.filter(q=>q.status==='Viewed').length)}
function renderMetrics(){document.querySelector('[data-metric="draft"]').textContent=state.quotes.filter(q=>q.status==='Draft').length;document.querySelector('[data-metric="sent"]').textContent=state.quotes.filter(q=>['Sent','Viewed'].includes(q.status)).length;document.querySelector('[data-metric="pending"]').textContent=state.quotes.filter(q=>q.status==='Viewed').length;document.querySelector('[data-metric="approved"]').textContent=money(state.quotes.filter(q=>q.status==='Approved').reduce((s,q)=>s+total(q),0))}
function renderDashboard(){const recent=state.quotes.slice().sort((a,b)=>b.created.localeCompare(a.created)||b.version-a.version).slice(0,5);document.querySelector('[data-dashboard-quotes]').innerHTML=recent.map(q=>`<div class="quote-row"><div><strong>${esc(q.client)} · ${esc(q.title)}</strong><small>${q.series} · v${q.version} · ${esc(q.contact)}</small></div><span>${money(total(q))}</span><span class="status ${statusClass(q.status)}">${q.status}</span></div>`).join('')||'<p>견적 데이터가 없습니다.</p>';const order=['Draft','Sent','Viewed','Approved','Declined'];document.querySelector('[data-status-mix]').innerHTML=order.map(s=>`<div class="mix-row"><span>${s}</span><b>${state.quotes.filter(q=>q.status===s).length}</b></div>`).join('');const pending=state.quotes.filter(q=>q.status==='Viewed').slice(0,4);document.querySelector('[data-approval-mini]').innerHTML=pending.map(q=>`<div class="approval-mini-row"><span>${esc(q.client)} · v${q.version}</span><b>${money(total(q))}</b></div>`).join('')||'<div class="approval-mini-row"><span>승인 대기 없음</span><b>—</b></div>'}
function renderQuotes(){const tbody=document.querySelector('[data-quotes-table]');tbody.innerHTML=visibleQuotes().sort((a,b)=>b.created.localeCompare(a.created)).map(q=>`<tr><td><div class="quote-cell"><strong>${esc(q.title)}</strong><span>${q.series} · ${esc(q.contact)}</span></div></td><td>${esc(q.client)}</td><td>v${q.version}</td><td>${money(total(q))}</td><td>${esc(q.valid)}</td><td><span class="status ${statusClass(q.status)}">${q.status}</span></td><td><div class="action-group"><button class="tiny-button" data-edit="${q.uid}">편집</button><button class="tiny-button" data-cycle="${q.uid}">상태</button><button class="tiny-button" data-clone="${q.uid}">새 버전</button></div></td></tr>`).join('')||'<tr><td colspan="7">조건에 맞는 견적이 없습니다.</td></tr>';tbody.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>loadBuilder(b.dataset.edit)));tbody.querySelectorAll('[data-cycle]').forEach(b=>b.addEventListener('click',()=>cycleStatus(b.dataset.cycle)));tbody.querySelectorAll('[data-clone]').forEach(b=>b.addEventListener('click',()=>cloneVersion(b.dataset.clone)))}
function renderVersions(){const groups={};state.quotes.forEach(q=>(groups[q.series]||(groups[q.series]=[])).push(q));document.querySelector('[data-version-grid]').innerHTML=Object.entries(groups).sort((a,b)=>b[0].localeCompare(a[0])).map(([series,list])=>{const sorted=list.sort((a,b)=>b.version-a.version);const latest=sorted[0];return `<article class="version-card"><h3>${esc(latest.client)}</h3><p>${esc(latest.title)} · ${series}</p><div class="version-meta"><div><span>Latest</span><b>v${latest.version}</b></div><div><span>Versions</span><b>${sorted.length}</b></div><div><span>Total</span><b>${money(total(latest))}</b></div><div><span>Status</span><b>${latest.status}</b></div></div><div class="card-actions"><button data-version-open="${latest.uid}">최신본 편집</button><button data-version-clone="${latest.uid}">새 버전</button></div></article>`}).join('');document.querySelectorAll('[data-version-open]').forEach(b=>b.addEventListener('click',()=>loadBuilder(b.dataset.versionOpen)));document.querySelectorAll('[data-version-clone]').forEach(b=>b.addEventListener('click',()=>cloneVersion(b.dataset.versionClone)))}
function renderApproval(){const rows=state.quotes.filter(q=>q.status!=='Draft').sort((a,b)=>b.created.localeCompare(a.created));document.querySelector('[data-approval-grid]').innerHTML=rows.map(q=>`<article class="approval-card"><h3>${esc(q.client)}</h3><p>${esc(q.title)} · ${q.series} · v${q.version}</p><div class="approval-meta"><div><span>Amount</span><b>${money(total(q))}</b></div><div><span>Status</span><b>${q.status}</b></div><div><span>Contact</span><b>${esc(q.contact)}</b></div><div><span>Valid</span><b>${esc(q.valid)}</b></div></div><div class="card-actions"><button data-mark-viewed="${q.uid}">열람 처리</button><button data-approve="${q.uid}">승인</button><button data-decline="${q.uid}">거절</button></div></article>`).join('')||'<p>발송된 견적이 없습니다.</p>';document.querySelectorAll('[data-mark-viewed]').forEach(b=>b.addEventListener('click',()=>setStatus(b.dataset.markViewed,'Viewed')));document.querySelectorAll('[data-approve]').forEach(b=>b.addEventListener('click',()=>setStatus(b.dataset.approve,'Approved')));document.querySelectorAll('[data-decline]').forEach(b=>b.addEventListener('click',()=>setStatus(b.dataset.decline,'Declined')))}
function syncBuilderFromInputs(){builder.client=document.querySelector('[data-builder-client]').value.trim();builder.title=document.querySelector('[data-builder-title]').value.trim();builder.valid=document.querySelector('[data-builder-valid]').value;builder.items=[...document.querySelectorAll('.builder-item')].map(row=>({name:row.querySelector('[data-item-name]').value.trim(),qty:Number(row.querySelector('[data-item-qty]').value)||0,unit:Number(row.querySelector('[data-item-unit]').value)||0}));renderPreview()}
function renderBuilder(){document.querySelector('[data-builder-client]').value=builder.client||'';document.querySelector('[data-builder-title]').value=builder.title||'';document.querySelector('[data-builder-valid]').value=builder.valid||'';document.querySelector('[data-builder-version]').value='v'+(builder.version||1);document.querySelector('[data-builder-items]').innerHTML=(builder.items||[]).map((i,index)=>`<div class="builder-item"><input data-item-name value="${esc(i.name)}" placeholder="항목명"><input data-item-qty type="number" min="0" step="1" value="${Number(i.qty)||0}"><input data-item-unit type="number" min="0" step="10000" value="${Number(i.unit)||0}"><b>${money((Number(i.qty)||0)*(Number(i.unit)||0))}</b><button type="button" data-remove-item="${index}" aria-label="항목 삭제">×</button></div>`).join('');document.querySelectorAll('.builder-item input').forEach(el=>el.addEventListener('input',syncBuilderFromInputs));document.querySelectorAll('[data-remove-item]').forEach(b=>b.addEventListener('click',()=>{builder.items.splice(Number(b.dataset.removeItem),1);renderBuilder()}));renderPreview()}
function renderPreview(){const q={items:builder.items||[]};document.querySelector('[data-preview-title]').textContent=builder.title||'새 견적';document.querySelector('[data-preview-client]').textContent=builder.client||'고객사를 입력하세요';document.querySelector('[data-preview-items]').innerHTML=(builder.items||[]).map(i=>`<div class="quote-doc-row"><span>${esc(i.name||'미입력')}</span><span>${Number(i.qty)||0}</span><span>${money(Number(i.unit)||0)}</span><span>${money((Number(i.qty)||0)*(Number(i.unit)||0))}</span></div>`).join('');const sub=subtotal(q);document.querySelector('[data-preview-subtotal]').textContent=money(sub);document.querySelector('[data-preview-vat]').textContent=money(Math.round(sub*.1));document.querySelector('[data-preview-total]').textContent=money(Math.round(sub*1.1))}
function loadBuilder(uid){const q=state.quotes.find(x=>x.uid===uid);if(!q)return;builder={uid:q.uid,client:q.client,title:q.title,valid:q.valid,version:q.version,items:JSON.parse(JSON.stringify(q.items))};renderBuilder();setView('builder');toast('견적을 Builder에 불러왔습니다.')}
function newest(){return state.quotes.slice().sort((a,b)=>b.created.localeCompare(a.created)||b.version-a.version)[0]}
function saveBuilderQuote(){syncBuilderFromInputs();if(!builder.client||!builder.title||!builder.items.length){toast('고객사, 제목과 견적 항목을 입력해주세요.');return}if(builder.uid){const q=state.quotes.find(x=>x.uid===builder.uid);if(q){q.client=builder.client;q.title=builder.title;q.valid=builder.valid;q.items=JSON.parse(JSON.stringify(builder.items));q.status='Draft'}}else{const next=String(26000+state.quotes.length+20);const today=new Date().toISOString().slice(0,10);const q={uid:'q'+Date.now(),series:'QT-'+next,client:builder.client,contact:'담당자 미지정',title:builder.title,version:1,valid:builder.valid||today,created:today,status:'Draft',items:JSON.parse(JSON.stringify(builder.items))};state.quotes.unshift(q);builder.uid=q.uid;builder.version=1}saveState();renderAll();toast('견적을 Draft로 저장했습니다.')}
function cloneVersion(uid){const q=state.quotes.find(x=>x.uid===uid);if(!q)return;const maxVersion=Math.max(...state.quotes.filter(x=>x.series===q.series).map(x=>x.version));const copy={...JSON.parse(JSON.stringify(q)),uid:'q'+Date.now(),version:maxVersion+1,created:new Date().toISOString().slice(0,10),status:'Draft'};state.quotes.unshift(copy);saveState();renderAll();loadBuilder(copy.uid);toast(`v${copy.version} 새 버전을 만들었습니다.`)}
function setStatus(uid,status){const q=state.quotes.find(x=>x.uid===uid);if(!q)return;q.status=status;saveState();renderAll();toast(`상태 변경: ${status}`)}
function cycleStatus(uid){const q=state.quotes.find(x=>x.uid===uid);if(!q)return;const order=['Draft','Sent','Viewed','Approved','Declined'];q.status=order[(order.indexOf(q.status)+1)%order.length];saveState();renderAll();toast(`상태 변경: ${q.status}`)}
document.querySelector('[data-builder-client]').addEventListener('input',syncBuilderFromInputs);document.querySelector('[data-builder-title]').addEventListener('input',syncBuilderFromInputs);document.querySelector('[data-builder-valid]').addEventListener('input',syncBuilderFromInputs);document.querySelector('[data-add-item]').addEventListener('click',()=>{syncBuilderFromInputs();builder.items.push({name:'New Service Item',qty:1,unit:500000});renderBuilder()});document.querySelector('[data-save-builder]').addEventListener('click',saveBuilderQuote);document.querySelector('[data-load-latest]').addEventListener('click',()=>{const q=newest();if(q)loadBuilder(q.uid)});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{currentFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('is-active',x===b));renderQuotes()}));document.querySelector('[data-search]').addEventListener('input',e=>{searchQuery=e.target.value.trim();renderQuotes()});
function openModal(){const m=document.querySelector('[data-modal="quote"]');m.classList.add('is-open');m.setAttribute('aria-hidden','false');m.querySelector('input')?.focus()}
function closeModal(){const m=document.querySelector('[data-modal="quote"]');m.classList.remove('is-open');m.setAttribute('aria-hidden','true')}
document.querySelector('[data-open-quote]').addEventListener('click',openModal);document.querySelector('[data-close]').addEventListener('click',closeModal);document.querySelector('[data-modal="quote"]').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelector('[data-quote-form]').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const next=String(26000+state.quotes.length+20);const amount=Number(fd.get('amount'))||0;const today=new Date().toISOString().slice(0,10);const q={uid:'q'+Date.now(),series:'QT-'+next,client:fd.get('client').trim(),contact:fd.get('contact').trim(),title:fd.get('title').trim(),version:1,valid:fd.get('valid'),created:today,status:'Draft',items:[{name:'Project Scope',qty:1,unit:amount}]};state.quotes.unshift(q);saveState();e.currentTarget.reset();closeModal();renderAll();loadBuilder(q.uid);toast('새 견적을 생성했습니다.')});
document.querySelector('[data-reset]').addEventListener('click',()=>{if(!confirm('QuoteFlow 데모 데이터를 초기화할까요?'))return;state=cloneSeed();saveState();builder={uid:null,client:'',title:'',valid:'2026-09-30',version:1,items:[{name:'Website Planning & Design',qty:1,unit:2500000},{name:'Responsive Development',qty:1,unit:1800000}]};renderAll();setView('dashboard');toast('데모 데이터를 초기화했습니다.')});
const params=new URLSearchParams(location.search);const initial=params.get('view');renderAll();setView(['dashboard','quotes','builder','versions','approval'].includes(initial)?initial:'dashboard');
