const STORAGE_KEY='aesost-support-desk-demo-v1';
const team=[{id:'a1',name:'김도윤',role:'Technical Support'},{id:'a2',name:'이서진',role:'Customer Success'},{id:'a3',name:'박하린',role:'Operations'}];
const seed={tickets:[
{id:'T-260901',subject:'관리자 페이지 로그인이 되지 않습니다',customer:'김민지',company:'오브젝트랩',category:'기술 지원',priority:'High',assignee:'a1',due:'2026-09-06',status:'In Progress',channel:'Email',notes:['브라우저 환경 확인 요청'],reopened:0},
{id:'T-260902',subject:'계약서 내 사업자 정보 수정 요청',customer:'정우성',company:'모리리빙',category:'결제/계약',priority:'Normal',assignee:'a3',due:'2026-09-07',status:'Assigned',channel:'Website',notes:[],reopened:0},
{id:'T-260903',subject:'포트폴리오 이미지 교체가 필요합니다',customer:'최유나',company:'스튜디오 모어',category:'콘텐츠 수정',priority:'Normal',assignee:'a2',due:'2026-09-08',status:'Waiting',channel:'Email',notes:['교체 이미지 수신 대기'],reopened:0},
{id:'T-260904',subject:'결제 완료했는데 서비스가 활성화되지 않았습니다',customer:'강현우',company:'아크헬스',category:'서비스 이용',priority:'High',assignee:'a1',due:'2026-09-06',status:'New',channel:'Phone',notes:[],reopened:0},
{id:'T-260905',subject:'뉴스 게시판 정렬 방식 문의',customer:'윤세아',company:'브릭앤코',category:'서비스 이용',priority:'Low',assignee:'a2',due:'2026-09-10',status:'Resolved',channel:'Website',notes:['정렬 옵션 안내 완료'],reopened:0},
{id:'T-260906',subject:'견적서 PDF 재발송 요청',customer:'한지민',company:'루프웍스',category:'결제/계약',priority:'Normal',assignee:'a3',due:'2026-09-09',status:'Reopened',channel:'Email',notes:['기존 메일 미수신으로 재오픈'],reopened:1}
]};
let state=loadState();
let searchQuery='';
let currentFilter='all';
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||cloneSeed()}catch{return cloneSeed()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function esc(value=''){return String(value).replace(/[&<>'\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[m]))}
function assignee(id){return team.find(x=>x.id===id)}
function statusClass(v){return v.replaceAll(' ','-')}
function toast(message){const el=document.querySelector('[data-toast]');if(!el)return;el.textContent=message;el.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('is-visible'),1800)}
function parseDate(v){return new Date(v+'T00:00:00')}
function formatDate(v){return new Intl.DateTimeFormat('ko-KR',{month:'2-digit',day:'2-digit'}).format(parseDate(v))}
function daysUntil(v){const now=new Date();now.setHours(0,0,0,0);return Math.ceil((parseDate(v)-now)/86400000)}
function openTickets(){return state.tickets.filter(t=>t.status!=='Resolved')}
function visibleTickets(){const q=searchQuery.toLowerCase();return state.tickets.filter(t=>(currentFilter==='all'||t.status===currentFilter)&&(!q||[t.id,t.subject,t.customer,t.company,t.category,assignee(t.assignee)?.name||''].some(v=>String(v).toLowerCase().includes(q))))}
function setView(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('is-active',b.dataset.view===name));document.querySelectorAll('[data-view-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.viewPanel===name));const titles={dashboard:'고객지원 현황',tickets:'문의 티켓',customers:'고객 지원 이력',team:'지원팀 업무량',insights:'지원 인사이트'};document.querySelector('[data-view-title]').textContent=titles[name]||'Support Desk'}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));
function renderAll(){renderCounts();renderMetrics();renderDashboard();renderTickets();renderCustomers();renderTeam();renderInsights();renderAssignees()}
function renderCounts(){document.querySelectorAll('[data-count="tickets"]').forEach(el=>el.textContent=openTickets().length)}
function renderMetrics(){const open=openTickets();const urgent=open.filter(t=>t.priority==='High');const sla=open.filter(t=>daysUntil(t.due)<=1);const resolved=state.tickets.filter(t=>t.status==='Resolved');document.querySelector('[data-metric="open"]').textContent=open.length;document.querySelector('[data-metric="urgent"]').textContent=urgent.length;document.querySelector('[data-metric="sla"]').textContent=sla.length;document.querySelector('[data-metric="resolved"]').textContent=resolved.length}
function renderDashboard(){const target=document.querySelector('[data-dashboard-tickets]');const rows=openTickets().slice().sort((a,b)=>{const p={High:0,Normal:1,Low:2};return p[a.priority]-p[b.priority]||parseDate(a.due)-parseDate(b.due)}).slice(0,5);target.innerHTML=rows.map(t=>`<div class="ticket-row"><div class="ticket-main"><strong>${esc(t.subject)}</strong><small>${esc(t.company)} · ${esc(t.customer)} · ${esc(assignee(t.assignee)?.name||'미배정')}</small></div><span class="priority ${t.priority}">${t.priority}</span><span class="status ${statusClass(t.status)}">${t.status}</span></div>`).join('')||'<p>열린 티켓이 없습니다.</p>';const categories={};state.tickets.forEach(t=>categories[t.category]=(categories[t.category]||0)+1);document.querySelector('[data-category-list]').innerHTML=Object.entries(categories).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="category-item"><b>${esc(k)}</b><span>${v}건</span></div>`).join('');document.querySelector('[data-team-mini]').innerHTML=team.map(a=>{const count=openTickets().filter(t=>t.assignee===a.id).length;return `<div class="team-mini-row"><b>${esc(a.name)}</b><span>${count} open</span></div>`}).join('')}
function renderTickets(){const tbody=document.querySelector('[data-tickets-table]');tbody.innerHTML=visibleTickets().map(t=>`<tr><td><div class="ticket-cell"><strong>${esc(t.subject)}</strong><span>${t.id} · ${esc(t.channel)}</span></div></td><td>${esc(t.company)}<br><small>${esc(t.customer)}</small></td><td>${esc(t.category)}</td><td><span class="priority ${t.priority}">${t.priority}</span></td><td>${esc(assignee(t.assignee)?.name||'미배정')}</td><td>${formatDate(t.due)}</td><td><span class="status ${statusClass(t.status)}">${t.status}</span></td><td><div class="action-group"><button class="tiny-button" data-status="${t.id}">상태</button><button class="tiny-button" data-assign="${t.id}">담당</button><button class="tiny-button" data-note="${t.id}">메모</button></div></td></tr>`).join('')||'<tr><td colspan="8">조건에 맞는 티켓이 없습니다.</td></tr>';tbody.querySelectorAll('[data-status]').forEach(b=>b.addEventListener('click',()=>cycleStatus(b.dataset.status)));tbody.querySelectorAll('[data-assign]').forEach(b=>b.addEventListener('click',()=>cycleAssignee(b.dataset.assign)));tbody.querySelectorAll('[data-note]').forEach(b=>b.addEventListener('click',()=>addNote(b.dataset.note)))}
function renderCustomers(){const map={};state.tickets.forEach(t=>{const key=t.company+'|'+t.customer;if(!map[key])map[key]={company:t.company,customer:t.customer,total:0,open:0,resolved:0};map[key].total++;if(t.status==='Resolved')map[key].resolved++;else map[key].open++});document.querySelector('[data-customer-grid]').innerHTML=Object.values(map).map(c=>`<article class="customer-card"><h3>${esc(c.company)}</h3><p>${esc(c.customer)} · 지원 이력</p><div class="card-stats"><div><span>전체 티켓</span><b>${c.total}</b></div><div><span>오픈</span><b>${c.open}</b></div><div><span>해결</span><b>${c.resolved}</b></div><div><span>해결률</span><b>${Math.round(c.resolved/c.total*100)}%</b></div></div></article>`).join('')}
function renderTeam(){document.querySelector('[data-team-grid]').innerHTML=team.map(a=>{const rows=state.tickets.filter(t=>t.assignee===a.id);const open=rows.filter(t=>t.status!=='Resolved').length;const urgent=rows.filter(t=>t.status!=='Resolved'&&t.priority==='High').length;const resolved=rows.filter(t=>t.status==='Resolved').length;return `<article class="team-card"><h3>${esc(a.name)}</h3><p>${esc(a.role)}</p><div class="card-stats"><div><span>Open</span><b>${open}</b></div><div><span>Urgent</span><b>${urgent}</b></div><div><span>Resolved</span><b>${resolved}</b></div><div><span>Total</span><b>${rows.length}</b></div></div></article>`}).join('')}
function renderInsights(){const total=state.tickets.length||1;const resolved=state.tickets.filter(t=>t.status==='Resolved').length;const urgent=state.tickets.filter(t=>t.priority==='High').length;const reopened=state.tickets.reduce((s,t)=>s+(t.reopened||0),0);document.querySelector('[data-insight-resolution]').textContent=Math.round(resolved/total*100)+'%';document.querySelector('[data-insight-urgent]').textContent=Math.round(urgent/total*100)+'%';document.querySelector('[data-insight-reopened]').textContent=reopened;const categories={};state.tickets.forEach(t=>categories[t.category]=(categories[t.category]||0)+1);const max=Math.max(...Object.values(categories),1);document.querySelector('[data-category-bars]').innerHTML=Object.entries(categories).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar-track"><i style="width:${Math.round(v/max*100)}%"></i></div><b>${v}</b></div>`).join('')}
function renderAssignees(){const select=document.querySelector('[data-assignee-select]');if(select)select.innerHTML=team.map(a=>`<option value="${a.id}">${esc(a.name)} · ${esc(a.role)}</option>`).join('')}
function cycleStatus(id){const t=state.tickets.find(x=>x.id===id);if(!t)return;const order=['New','Assigned','In Progress','Waiting','Resolved','Reopened'];const prev=t.status;t.status=order[(order.indexOf(t.status)+1)%order.length];if(t.status==='Reopened'&&prev!=='Reopened')t.reopened=(t.reopened||0)+1;saveState();renderAll();toast(`상태 변경: ${t.status}`)}
function cycleAssignee(id){const t=state.tickets.find(x=>x.id===id);if(!t)return;const i=team.findIndex(a=>a.id===t.assignee);t.assignee=team[(i+1)%team.length].id;if(t.status==='New')t.status='Assigned';saveState();renderAll();toast(`담당자: ${assignee(t.assignee).name}`)}
function addNote(id){const t=state.tickets.find(x=>x.id===id);if(!t)return;const note=prompt('내부 메모를 입력하세요.');if(!note?.trim())return;t.notes=t.notes||[];t.notes.push(note.trim());saveState();toast('내부 메모를 저장했습니다.')}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{currentFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('is-active',x===b));renderTickets()}));document.querySelector('[data-search]').addEventListener('input',e=>{searchQuery=e.target.value.trim();renderTickets()});
function openModal(){const m=document.querySelector('[data-modal="ticket"]');m.classList.add('is-open');m.setAttribute('aria-hidden','false');m.querySelector('input')?.focus()}
function closeModal(){const m=document.querySelector('[data-modal="ticket"]');m.classList.remove('is-open');m.setAttribute('aria-hidden','true')}
document.querySelector('[data-open-ticket]').addEventListener('click',openModal);document.querySelector('[data-close]').addEventListener('click',closeModal);document.querySelector('[data-modal="ticket"]').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelector('[data-ticket-form]').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const next=String(state.tickets.length+1).padStart(3,'0');state.tickets.unshift({id:'T-26'+next,subject:fd.get('subject').trim(),customer:fd.get('customer').trim(),company:fd.get('company').trim(),category:fd.get('category'),priority:fd.get('priority'),assignee:fd.get('assignee'),due:fd.get('due'),status:'New',channel:'Website',notes:[],reopened:0});saveState();e.currentTarget.reset();closeModal();renderAll();setView('tickets');toast('새 문의 티켓을 등록했습니다.')});
document.querySelector('[data-reset]').addEventListener('click',()=>{if(!confirm('Support Desk 데모 데이터를 초기화할까요?'))return;state=cloneSeed();saveState();renderAll();toast('데모 데이터를 초기화했습니다.')});
const params=new URLSearchParams(location.search);const initial=params.get('view');renderAll();setView(['dashboard','tickets','customers','team','insights'].includes(initial)?initial:'dashboard');
