function ensureHeadTag(selector,create){if(document.head.querySelector(selector))return;document.head.appendChild(create())}
function loadStylesheet(href){if(document.querySelector(`link[href="${href}"]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.appendChild(link)}
ensureHeadTag('link[rel="icon"]',()=>{const e=document.createElement('link');e.rel='icon';e.type='image/svg+xml';e.href='favicon.svg?v=20260802-1';return e});
ensureHeadTag('link[rel="manifest"]',()=>{const e=document.createElement('link');e.rel='manifest';e.href='site.webmanifest?v=20260802-1';return e});
ensureHeadTag('meta[name="theme-color"]',()=>{const e=document.createElement('meta');e.name='theme-color';e.content='#651DDC';return e});
ensureHeadTag('meta[name="description"]',()=>{const e=document.createElement('meta');e.name='description';e.content='AESOST는 질문과 경험을 연결해 커리어의 다음 방향을 구체화하는 플랫폼입니다.';return e});
loadStylesheet('refine.css');loadStylesheet('member-gate.css');loadStylesheet('mobile-spacing.css?v=20260802-1');loadStylesheet('grid-four.css?v=20260801-1');loadStylesheet('wavelab-philosophy.css?v=20260801-1');loadStylesheet('search-refine.css?v=20260801-1');loadStylesheet('image-fallback.css?v=20260801-2');loadStylesheet('aesost-theme.css?v=20260802-1');
const page=location.pathname.split('/').pop()||'index.html';
const nav=[['매거진','magazine.html'],['아티클','article.html'],['칼럼','column.html'],['클래스','class.html'],['전문가','expert-feedback.html'],['뉴스','news.html']];
function active(url){if(page===url)return true;if(url==='class.html'&&page==='study-detail.html')return true;return false}
function brandMarkup(){return '<img class="brand-logo" src="aesost-logo.svg?v=20260801-2" alt="AESOST">'}
function headerMarkup(){const navigation=nav.map(([name,url])=>`<a href="${url}" class="${active(url)?'is-active':''}">${name}</a>`).join('');return `<div class="header-inner shell"><a class="brand" href="index.html" aria-label="AESOST 홈으로 이동">${brandMarkup()}</a><nav class="desktop-nav" aria-label="주요 메뉴">${navigation}</nav><div class="header-actions"><input class="search-box" type="text" placeholder="검색" data-search-open readonly aria-label="검색 열기"><a class="cta" href="column-write.html" data-column-write hidden>칼럼 쓰기</a><a class="login" href="login.html" data-auth-login>로그인</a><a class="mypage-link" href="mypage.html" data-auth-mypage hidden>마이페이지</a><a class="logout-link" href="#" data-auth-logout hidden>로그아웃</a><button class="menu-btn" type="button" data-menu aria-label="메뉴 열기" aria-expanded="false"><i></i><i></i><i></i></button></div></div><nav class="mobile-nav" data-mobile aria-label="모바일 메뉴">${navigation}<a href="column-write.html" data-mobile-column-write hidden>칼럼 쓰기</a><a href="login.html" data-mobile-login>로그인</a><a href="mypage.html" data-mobile-mypage hidden>마이페이지</a><a href="#" data-mobile-logout hidden>로그아웃</a></nav>`}
function footerMarkup(){return `<div class="shell"><div class="footer-grid"><div><a class="brand" href="index.html">${brandMarkup()}</a><p>질문과 경험을 연결하고, 커리어의 다음 선택을 구체화하는 플랫폼.</p></div><div><h3>CONTENT</h3><nav><a href="magazine.html">매거진</a><a href="article.html">아티클</a><a href="column.html">칼럼</a><a href="class.html">클래스</a><a href="news.html">뉴스</a></nav></div><div><h3>AESOST</h3><nav><a href="expert-feedback.html">전문가에게 고민 남기기</a><a href="columnist-apply.html">칼럼니스트 신청</a><a href="about.html">에이소스트 소개</a><a href="notice.html">공지사항</a></nav></div><div><h3>ACCOUNT</h3><nav><a href="login.html">로그인</a><a href="login.html?mode=signup">회원가입</a><a href="mypage.html">마이페이지</a><a href="ability-edit.html">커리어 아카이브</a></nav></div></div><div class="footer-bottom"><span>QUESTION · EXPERIENCE · DIRECTION</span><span>© 2026 AESOST.</span></div></div>`}
const header=document.querySelector('[data-header]'),footer=document.querySelector('[data-footer]');if(header)header.innerHTML=headerMarkup();if(footer)footer.innerHTML=footerMarkup();
const menuButton=document.querySelector('[data-menu]'),mobileMenu=document.querySelector('[data-mobile]');menuButton?.addEventListener('click',()=>{const opened=mobileMenu.classList.toggle('is-open');menuButton.classList.toggle('is-open',opened);menuButton.setAttribute('aria-expanded',String(opened))});mobileMenu?.querySelectorAll('a,button').forEach(item=>item.addEventListener('click',()=>{mobileMenu.classList.remove('is-open');menuButton?.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false')}));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const group=button.closest('.filters');group?.querySelectorAll('[data-filter]').forEach(item=>item.classList.remove('is-active'));button.classList.add('is-active');const selected=button.dataset.filter;document.querySelectorAll('[data-category]').forEach(card=>{card.hidden=selected!=='전체'&&card.dataset.category!==selected})}));
const searchPanel=document.querySelector('[data-search-panel]');document.querySelectorAll('[data-search-open]').forEach(button=>button.addEventListener('click',()=>{searchPanel?.classList.add('is-open');searchPanel?.querySelector('input')?.focus()}));searchPanel?.querySelector('[data-search-close]')?.addEventListener('click',()=>searchPanel.classList.remove('is-open'));document.addEventListener('keydown',event=>{if(event.key==='Escape')searchPanel?.classList.remove('is-open')});
function activateAuthTab(name){document.querySelectorAll('[data-auth-tab]').forEach(item=>item.classList.toggle('is-active',item.dataset.authTab===name));document.querySelectorAll('[data-auth-panel]').forEach(panel=>panel.classList.toggle('is-active',panel.dataset.authPanel===name))}document.querySelectorAll('[data-auth-tab]').forEach(tab=>tab.addEventListener('click',()=>activateAuthTab(tab.dataset.authTab)));const authMode=new URLSearchParams(location.search).get('mode');if(authMode==='signup'||location.hash==='#signup')activateAuthTab('signup');
const gatedPages=new Set(['magazine.html','article.html','column.html','class.html','news.html']);
function applyMemberAccess(user=null){if(!gatedPages.has(page))return;const grid=document.querySelector('.grid,.study-grid');if(!grid)return;const cards=[...grid.querySelectorAll(':scope > .card,:scope > .study-card')],signed=Boolean(user);cards.forEach((card,index)=>{if(!card.dataset.originalHref)card.dataset.originalHref=card.getAttribute('href')||'#';if(index<4||signed){card.classList.remove('member-locked');card.setAttribute('href',card.dataset.originalHref);card.querySelector('.member-lock-overlay')?.remove();return}card.classList.add('member-locked');card.setAttribute('href',`login.html?mode=signup&next=${encodeURIComponent(card.dataset.originalHref)}`);const thumb=card.querySelector('.thumb,.real-thumb');if(thumb&&!thumb.querySelector('.member-lock-overlay'))thumb.insertAdjacentHTML('beforeend','<div class="member-lock-overlay"><span class="member-lock-icon">⌑</span><strong>MEMBERS ONLY</strong><span>에이소스트 시작하기</span></div>')});let banner=grid.querySelector('.member-gate-banner');if(!signed&&cards.length>4&&!banner){banner=document.createElement('div');banner.className='member-gate-banner';banner.innerHTML='<div class="member-gate-philosophy"><span>ASK · LEARN · WRITE · MOVE</span><h3>다른 사람의 경험을 읽고, 자신의 질문과 경험도 커리어 자산으로 남겨보세요.</h3><p>에이소스트에서 전체 콘텐츠를 읽고, 전문가에게 고민을 남기며, 자신의 경험과 관점을 기록할 수 있습니다.</p></div><a href="login.html?mode=signup">에이소스트 시작하기</a>';grid.insertBefore(banner,cards[4])}if(signed)banner?.remove()}
window.applyMemberAccess=applyMemberAccess;applyMemberAccess(null);
const firebaseModule=document.createElement('script');firebaseModule.type='module';firebaseModule.src='firebase-auth.js?v=20260801-2';document.body.appendChild(firebaseModule);
const columnistModule=document.createElement('script');columnistModule.type='module';columnistModule.src='columnist-access.js?v=20260801-2';document.body.appendChild(columnistModule);
const enhance=document.createElement('script');enhance.src='site-enhance.js?v=20260801-4';document.body.appendChild(enhance);
document.title=document.title.replaceAll('WAVELAB','AESOST').replaceAll('웨이블랩','에이소스트');
document.querySelectorAll('meta[name="description"],meta[property="og:site_name"],meta[property="og:title"],meta[property="og:description"]').forEach(meta=>{if(meta.content)meta.content=meta.content.replaceAll('WAVELAB','AESOST').replaceAll('웨이블랩','에이소스트')});