function loadStylesheet(href){if(document.querySelector(`link[href="${href}"]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.appendChild(link)}
loadStylesheet('refine.css');loadStylesheet('member-gate.css');
const page=location.pathname.split('/').pop()||'index.html';
const nav=[['매거진','magazine.html'],['아티클','article.html'],['칼럼','column.html'],['클래스','class.html'],['커뮤니티','community.html'],['뉴스','news.html']];
function active(url){if(page===url)return true;if(url==='community.html'&&page.startsWith('community-'))return true;if(url==='class.html'&&page==='study-detail.html')return true;return false}
function headerMarkup(){const navigation=nav.map(([name,url])=>`<a href="${url}" class="${active(url)?'is-active':''}">${name}</a>`).join('');return `<div class="header-inner shell"><a class="brand" href="index.html" aria-label="WAVELAB 홈으로 이동"><span class="brand-mark" aria-hidden="true">✦</span><span>WAVELAB</span></a><nav class="desktop-nav" aria-label="주요 메뉴">${navigation}</nav><div class="header-actions"><input class="search-box" type="text" placeholder="검색" data-search-open readonly aria-label="검색 열기"><a class="login" href="login.html" data-auth-login>로그인</a><a class="mypage-link" href="mypage.html" data-auth-mypage hidden>마이페이지</a><a class="logout-link" href="#" data-auth-logout hidden>로그아웃</a><a class="cta" href="class.html">시작하기</a><button class="menu-btn" type="button" data-menu aria-label="메뉴 열기" aria-expanded="false"><i></i><i></i></button></div></div><nav class="mobile-nav" data-mobile aria-label="모바일 메뉴"><a href="index.html">홈</a>${navigation}<a href="notice.html">공지사항</a><a href="about.html">웨이블랩 소개</a><a href="login.html" data-mobile-login>로그인</a><a href="mypage.html" data-mobile-mypage hidden>마이페이지</a><a href="#" data-mobile-logout hidden>로그아웃</a><button type="button" data-search-open>검색</button></nav>`}
function footerMarkup(){return `<div class="shell"><div class="footer-grid"><div><a class="brand" href="index.html"><span class="brand-mark">✦</span><span>WAVELAB</span></a><p>디자인, 기획, 개발과 비즈니스를 연결해 배우고 직접 만드는 올라운더 실무 학습 플랫폼.</p></div><div><h3>CONTENT</h3><nav><a href="magazine.html">매거진</a><a href="article.html">아티클</a><a href="column.html">칼럼</a><a href="class.html">클래스</a><a href="community.html">커뮤니티</a><a href="news.html">뉴스</a></nav></div><div><h3>WAVELAB</h3><nav><a href="notice.html">공지사항</a><a href="about.html">웨이블랩 소개</a><a href="#">문의하기</a><a href="#">인스타그램</a></nav></div><div><h3>ACCOUNT</h3><nav><a href="login.html">로그인</a><a href="login.html?mode=signup">회원가입</a><a href="mypage.html">마이페이지</a><a href="#">개인정보처리방침</a></nav></div></div><div class="footer-bottom"><span>LEARN. CONNECT. MAKE.</span><span>© 2026 WAVELAB.</span></div></div>`}
const header=document.querySelector('[data-header]'),footer=document.querySelector('[data-footer]');if(header)header.innerHTML=headerMarkup();if(footer)footer.innerHTML=footerMarkup();
const menuButton=document.querySelector('[data-menu]'),mobileMenu=document.querySelector('[data-mobile]');menuButton?.addEventListener('click',()=>{const opened=mobileMenu.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(opened))});mobileMenu?.querySelectorAll('a,button').forEach(item=>item.addEventListener('click',()=>{mobileMenu.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false')}));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const group=button.closest('.filters');group?.querySelectorAll('[data-filter]').forEach(item=>item.classList.remove('is-active'));button.classList.add('is-active');const selected=button.dataset.filter;document.querySelectorAll('[data-category]').forEach(card=>{card.hidden=selected!=='전체'&&card.dataset.category!==selected})}));
const searchPanel=document.querySelector('[data-search-panel]');document.querySelectorAll('[data-search-open]').forEach(button=>button.addEventListener('click',()=>{searchPanel?.classList.add('is-open');searchPanel?.querySelector('input')?.focus()}));searchPanel?.querySelector('[data-search-close]')?.addEventListener('click',()=>searchPanel.classList.remove('is-open'));document.addEventListener('keydown',event=>{if(event.key==='Escape')searchPanel?.classList.remove('is-open')});
function activateAuthTab(name){document.querySelectorAll('[data-auth-tab]').forEach(item=>item.classList.toggle('is-active',item.dataset.authTab===name));document.querySelectorAll('[data-auth-panel]').forEach(panel=>panel.classList.toggle('is-active',panel.dataset.authPanel===name))}document.querySelectorAll('[data-auth-tab]').forEach(tab=>tab.addEventListener('click',()=>activateAuthTab(tab.dataset.authTab)));const authMode=new URLSearchParams(location.search).get('mode');if(authMode==='signup'||location.hash==='#signup')activateAuthTab('signup');
const gatedPages=new Set(['magazine.html','article.html','column.html','class.html','news.html']);
function applyMemberAccess(user=null){if(!gatedPages.has(page))return;const grid=document.querySelector('.grid,.study-grid');if(!grid)return;const cards=[...grid.querySelectorAll(':scope > .card,:scope > .study-card')],signed=Boolean(user);cards.forEach((card,index)=>{if(!card.dataset.originalHref)card.dataset.originalHref=card.getAttribute('href')||'#';if(index<4||signed){card.classList.remove('member-locked');card.setAttribute('href',card.dataset.originalHref);card.querySelector('.member-lock-overlay')?.remove();return}card.classList.add('member-locked');card.setAttribute('href',`login.html?mode=signup&next=${encodeURIComponent(card.dataset.originalHref)}`);const thumb=card.querySelector('.thumb');if(thumb&&!thumb.querySelector('.member-lock-overlay'))thumb.insertAdjacentHTML('beforeend','<div class="member-lock-overlay"><span class="member-lock-icon">⌑</span><strong>MEMBERS ONLY</strong><span>회원가입하고 계속 보기</span></div>')});let banner=grid.querySelector('.member-gate-banner');if(!signed&&cards.length>4&&!banner){banner=document.createElement('div');banner.className='member-gate-banner';banner.innerHTML='<div><h3>더 많은 콘텐츠가 준비되어 있습니다.</h3><p>무료 회원가입 후 전체 콘텐츠를 계속 확인하세요.</p></div><a href="login.html?mode=signup">무료로 가입하기</a>';grid.insertBefore(banner,cards[4])}if(signed)banner?.remove()}
window.applyMemberAccess=applyMemberAccess;applyMemberAccess(null);const firebaseModule=document.createElement('script');firebaseModule.type='module';firebaseModule.src='firebase-auth.js?v=20260731-4';document.body.appendChild(firebaseModule);