const STORAGE_KEY='aesost-vendor-desk-demo-v1';
const DEMO_TODAY=new Date('2026-09-06T00:00:00');
const seed={
  vendors:[
    {id:'v1',name:'한울패키지',contact:'김지훈',phone:'02-6210-4481',category:'Packaging'},
    {id:'v2',name:'대진머티리얼즈',contact:'이수연',phone:'031-771-2045',category:'Raw Material'},
    {id:'v3',name:'성우프린팅',contact:'박현우',phone:'02-498-7812',category:'Printing'},
    {id:'v4',name:'미래로지스',contact:'최유진',phone:'032-881-3320',category:'Logistics'}
  ],
  orders:[
    {id:'PO-2609-014',vendor:'v1',item:'Folding carton / Ivory 350g',qty:5000,unit:680,due:'2026-09-12',status:'In Production'},
    {id:'PO-2609-013',vendor:'v2',item:'Royal ivory board 350g',qty:8000,unit:420,due:'2026-09-14',status:'Delayed'},
    {id:'PO-2609-012',vendor:'v3',item:'Premium label printing',qty:12000,unit:190,due:'2026-09-11',status:'In Transit'},
    {id:'PO-2609-011',vendor:'v4',item:'Finished goods delivery',qty:36,unit:85000,due:'2026-09-09',status:'Ordered'},
    {id:'PO-2608-028',vendor:'v1',item:'Rigid box / Navy',qty:2000,unit:1650,due:'2026-09-03',status:'Received'}
  ],
  settlements:[
    {po:'PO-2609-014',status:'Pending'},
    {po:'PO-2609-013',status:'Pending'},
    {po:'PO-2609-012',status:'Pending'},
    {po:'PO-2609-011',status:'Pending'},
    {po:'PO-2608-028',status:'Paid'}
  ]
};
let state=loadState();let filter='all';let query='';
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||cloneSeed()}catch{return cloneSeed()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function vendor(id){return state.vendors.find(v=>v.id===id)}
function order(id){return state.orders.find(o=>o.id===id)}
function settlement(id){return state.settlements.find(s=>s.po===id)}
function amount(o){return Number(o.qty)*Number(o.unit)}
function won(v){return '₩'+Math.round(v).toLocaleString('ko-KR')}
function esc(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function statusClass(v){return String(v).replaceAll(' ','-')}
function fmtDate(v){const d=new Date(v+'T00:00:00');return new Intl.DateTimeFormat('en',{month:'short',day:'2-digit'}).format(d)}
function toast(message){const el=document.querySelector('[data-toast]');el.textContent=message;el.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('is-visible'),1700)}
function setView(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('is-active',b.dataset.view===name));document.querySelectorAll('[data-view-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.viewPanel===name));const titles={dashboard:'발주·납기 현황',vendors:'협력사 데이터베이스',orders:'발주 관리',deliveries:'납기·입고 관리',settlements:'정산 현황'};document.querySelector('[data-view-title]').textContent=titles[name]||'Vendor Desk'}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));
function render(){renderCounts();renderMetrics();renderDashboard();renderVendors();renderOrders();renderDeliveries();renderSettlements();renderVendorSelect()}
function renderCounts(){document.querySelectorAll('[data-count="vendors"]').forEach(e=>e.textContent=state.vendors.length);document.querySelectorAll('[data-count="orders"]').forEach(e=>e.textContent=state.orders.length)}
function renderMetrics(){const open=state.orders.filter(o=>o.status!=='Received').length;const next=new Date(DEMO_TODAY);next.setDate(next.getDate()+7);const due=state.orders.filter(o=>{const d=new Date(o.due+'T00:00:00');return o.status!=='Received'&&d>=DEMO_TODAY&&d<=next}).length;const delayed=state.orders.filter(o=>o.status==='Delayed').length;const outstanding=state.settlements.filter(s=>s.status==='Pending').reduce((sum,s)=>sum+amount(order(s.po)||{qty:0,unit:0}),0);document.querySelector('[data-metric="open"]').textContent=open;document.querySelector('[data-metric="due"]').textContent=due;document.querySelector('[data-metric="delayed"]').textContent=delayed;document.querySelector('[data-metric="outstanding"]').textContent=won(outstanding);document.querySelector('[data-payable-total]').textContent=won(outstanding)}
function renderDashboard(){const active=state.orders.filter(o=>o.status!=='Received').sort((a,b)=>new Date(a.due)-new Date(b.due)).slice(0,5);document.querySelector('[data-dashboard-orders]').innerHTML=active.map(o=>`<div class="order-row"><div><strong>${esc(o.id)}</strong><small>${esc(vendor(o.vendor)?.name||'-')}</small></div><div><strong>${esc(o.item)}</strong><small>${o.qty.toLocaleString()} × ${won(o.unit)}</small></div><span>${fmtDate(o.due)}</span><span class="status ${statusClass(o.status)}">${o.status}</span></div>`).join('')||'<p>진행 중 발주가 없습니다.</p>';const alerts=state.orders.filter(o=>o.status!=='Received').sort((a,b)=>new Date(a.due)-new Date(b.due)).slice(0,4);document.querySelector('[data-delivery-alerts]').innerHTML=alerts.map(o=>`<div class="alert-item"><div><strong>${esc(o.item)}</strong><small>${esc(vendor(o.vendor)?.name||'-')} · ${fmtDate(o.due)}</small></div>${o.status==='Delayed'?'<em>DELAYED</em>':`<span>${esc(o.status)}</span>`}</div>`).join('');const pending=state.settlements.filter(s=>s.status==='Pending').slice(0,4);document.querySelector('[data-payable-list]').innerHTML=pending.map(s=>{const o=order(s.po);return `<div class="payable-item"><div><strong>${esc(s.po)}</strong><small>${esc(vendor(o?.vendor)?.name||'-')}</small></div><span>${won(o?amount(o):0)}</span></div>`}).join('')||'<p>정산 대기가 없습니다.</p>'}
function renderVendors(){const q=query.toLowerCase();const rows=state.vendors.filter(v=>!q||[v.name,v.contact,v.category].some(x=>x.toLowerCase().includes(q)));document.querySelector('[data-vendors-table]').innerHTML=rows.map(v=>{const os=state.orders.filter(o=>o.vendor===v.id);return `<tr><td><div class="vendor-name"><strong>${esc(v.name)}</strong><span>${esc(v.contact)} · ${esc(v.phone)}</span></div></td><td>${esc(v.contact)}</td><td>${esc(v.category)}</td><td>${os.length}</td><td>${won(os.reduce((s,o)=>s+amount(o),0))}</td></tr>`}).join('')||'<tr><td colspan="5">검색 결과가 없습니다.</td></tr>'}
function renderOrders(){const q=query.toLowerCase();const rows=state.orders.filter(o=>(filter==='all'||o.status===filter)&&(!q||[o.id,o.item,vendor(o.vendor)?.name||''].some(x=>x.toLowerCase().includes(q))));document.querySelector('[data-orders-table]').innerHTML=rows.map(o=>`<tr><td><strong>${esc(o.id)}</strong></td><td>${esc(vendor(o.vendor)?.name||'-')}</td><td>${esc(o.item)}</td><td>${Number(o.qty).toLocaleString()}</td><td>${won(amount(o))}</td><td>${fmtDate(o.due)}</td><td><button class="status-button" data-cycle="${o.id}" title="상태 변경"><span class="status ${statusClass(o.status)}">${o.status}</span></button></td></tr>`).join('')||'<tr><td colspan="7">조건에 맞는 발주가 없습니다.</td></tr>';document.querySelectorAll('[data-cycle]').forEach(b=>b.addEventListener('click',()=>cycleOrder(b.dataset.cycle)))}
function renderDeliveries(){const rows=state.orders.slice().sort((a,b)=>new Date(a.due)-new Date(b.due));document.querySelector('[data-delivery-grid]').innerHTML=rows.map(o=>`<article class="delivery-card"><div class="delivery-card-top"><span>${esc(o.id)}</span><button class="status-button" data-delivery-cycle="${o.id}"><span class="status ${statusClass(o.status)}">${o.status}</span></button></div><h3>${esc(o.item)}</h3><p>${esc(vendor(o.vendor)?.name||'-')}</p><div class="delivery-meta"><div><span>DUE</span><b>${fmtDate(o.due)}</b></div><div><span>AMOUNT</span><b>${won(amount(o))}</b></div></div></article>`).join('');document.querySelectorAll('[data-delivery-cycle]').forEach(b=>b.addEventListener('click',()=>cycleOrder(b.dataset.deliveryCycle)))}
function renderSettlements(){const paid=state.settlements.filter(s=>s.status==='Paid').reduce((sum,s)=>sum+amount(order(s.po)||{qty:0,unit:0}),0);const pending=state.settlements.filter(s=>s.status==='Pending').reduce((sum,s)=>sum+amount(order(s.po)||{qty:0,unit:0}),0);const total=state.orders.reduce((sum,o)=>sum+amount(o),0);document.querySelector('[data-paid-total]').textContent=won(paid);document.querySelector('[data-pending-total]').textContent=won(pending);document.querySelector('[data-total-value]').textContent=won(total);document.querySelector('[data-settlement-table]').innerHTML=state.settlements.map(s=>{const o=order(s.po);return `<tr><td>${esc(s.po)}</td><td>${esc(vendor(o?.vendor)?.name||'-')}</td><td>${won(o?amount(o):0)}</td><td><span class="status ${statusClass(o?.status||'Ordered')}">${esc(o?.status||'-')}</span></td><td><button class="status-button" data-pay="${s.po}"><span class="status ${s.status}">${s.status}</span></button></td></tr>`}).join('');document.querySelectorAll('[data-pay]').forEach(b=>b.addEventListener('click',()=>togglePayment(b.dataset.pay)))}
function renderVendorSelect(){const select=document.querySelector('[data-vendor-select]');select.innerHTML='<option value="">협력사 선택</option>'+state.vendors.map(v=>`<option value="${v.id}">${esc(v.name)} · ${esc(v.category)}</option>`).join('')}
function cycleOrder(id){const o=order(id);if(!o)return;const path=['Ordered','In Production','In Transit','Received'];if(o.status==='Delayed'){o.status='In Transit'}else{o.status=path[(path.indexOf(o.status)+1)%path.length]||'Ordered'};saveState();render();toast(`발주 상태: ${o.status}`)}
function togglePayment(id){const s=settlement(id);if(!s)return;s.status=s.status==='Paid'?'Pending':'Paid';saveState();render();toast(`정산 상태: ${s.status}`)}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('is-active',x===b));renderOrders()}));document.querySelector('[data-search]').addEventListener('input',e=>{query=e.target.value.trim();renderVendors();renderOrders()});
function openModal(){const m=document.querySelector('[data-modal="order"]');m.classList.add('is-open');m.setAttribute('aria-hidden','false');m.querySelector('select,input')?.focus()}function closeModal(){const m=document.querySelector('[data-modal="order"]');m.classList.remove('is-open');m.setAttribute('aria-hidden','true')}
document.querySelector('[data-open-order]').addEventListener('click',openModal);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeModal));document.querySelector('[data-modal="order"]').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelector('[data-order-form]').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const n=state.orders.length+15;const po=`PO-26${String(new Date().getMonth()+1).padStart(2,'0')}-${String(n).padStart(3,'0')}`;const o={id:po,vendor:fd.get('vendor'),item:fd.get('item').trim(),qty:Number(fd.get('qty')),unit:Number(fd.get('unit')),due:fd.get('due'),status:fd.get('status')};state.orders.unshift(o);state.settlements.unshift({po,status:'Pending'});saveState();e.currentTarget.reset();closeModal();render();setView('orders');toast('새 발주를 등록했습니다.')});
document.querySelector('[data-reset]').addEventListener('click',()=>{if(!confirm('Vendor Desk 데모 데이터를 초기화할까요?'))return;state=cloneSeed();saveState();render();toast('데모 데이터를 초기화했습니다.')});
const params=new URLSearchParams(location.search);const requested=params.get('view');if(requested)setView(requested);if(params.get('guide')==='1')document.body.classList.add('is-guide');render();