const STORAGE_KEY='aesost-project-room-demo-v1';
const owners=[{id:'u1',name:'김도윤',role:'Project Lead'},{id:'u2',name:'이서진',role:'Designer'},{id:'u3',name:'박하린',role:'Developer'},{id:'u4',name:'정유진',role:'Client Partner'}];
const seed={tasks:[
{id:'t1',name:'메인 페이지 비주얼 방향 확정',owner:'u2',priority:'High',due:'2026-09-08',status:'Review'},
{id:'t2',name:'반응형 헤더 개발',owner:'u3',priority:'Normal',due:'2026-09-10',status:'In Progress'},
{id:'t3',name:'서비스 소개 문구 검수',owner:'u4',priority:'Normal',due:'2026-09-09',status:'Todo'},
{id:'t4',name:'CMS 포트폴리오 등록 기능',owner:'u3',priority:'High',due:'2026-09-12',status:'In Progress'},
{id:'t5',name:'브랜드 가이드 최종본 정리',owner:'u2',priority:'Low',due:'2026-09-15',status:'Done'},
{id:'t6',name:'QA 체크리스트 작성',owner:'u1',priority:'Normal',due:'2026-09-13',status:'Todo'}
],milestones:[
{id:'m1',date:'2026-09-07',title:'Design Review',desc:'메인·서브 페이지 디자인 검토'},
{id:'m2',date:'2026-09-12',title:'Development Review',desc:'주요 기능 개발 중간 점검'},
{id:'m3',date:'2026-09-18',title:'Client QA',desc:'클라이언트 검수 및 수정'},
{id:'m4',date:'2026-09-22',title:'Launch',desc:'최종 배포 및 운영 시작'}
],deliverables:[
{id:'d1',name:'Homepage Design v3',version:'v3.0',owner:'u2',status:'Pending',updated:'2026-09-06'},
{id:'d2',name:'Brand Guide Final',version:'v1.0',owner:'u2',status:'Approved',updated:'2026-09-05'},
{id:'d3',name:'CMS Prototype',version:'v0.8',owner:'u3',status:'Pending',updated:'2026-09-06'}
],feedback:[
{id:'f1',target:'Homepage Design v3',message:'메인 CTA 문구를 조금 더 직관적으로 수정해주세요.',author:'정유진',date:'2026-09-06'},
{id:'f2',target:'CMS Prototype',message:'포트폴리오 정렬 순서를 관리자에서 변경할 수 있으면 좋겠습니다.',author:'김도윤',date:'2026-09-06'}
]};
let state=loadState();let searchQuery='';let currentFilter='all';
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||cloneSeed()}catch{return cloneSeed()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function esc(value=''){return String(value).replace(/[&<>'\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[m]))}
function owner(id){return owners.find(x=>x.id===id)}
function statusClass(v){return v.replaceAll(' ','-')}
function toast(message){const el=document.querySelector('[data-toast]');if(!el)return;el.textContent=message;el.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('is-visible'),1800)}
function parseDate(v){return new Date(v+'T00:00:00')}
function formatDate(v){return new Intl.DateTimeFormat('ko-KR',{month:'2-digit',day:'2-digit'}).format(parseDate(v))}
function daysUntil(v){const now=new Date();now.setHours(0,0,0,0);return Math.ceil((parseDate(v)-now)/86400000)}
function setView(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('is-active',b.dataset.view===name));document.querySelectorAll('[data-view-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.viewPanel===name));const titles={dashboard:'프로젝트 현황',tasks:'업무 관리',timeline:'프로젝트 일정',deliverables:'산출물 검토',feedback:'피드백 기록'};document.querySelector('[data-view-title]').textContent=titles[name]||'Project Room'}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));
function visibleTasks(){const q=searchQuery.toLowerCase();return state.tasks.filter(t=>(currentFilter==='all'||t.status===currentFilter)&&(!q||[t.name,owner(t.owner)?.name||'',t.priority,t.status].some(v=>String(v).toLowerCase().includes(q))))}
function renderAll(){renderCounts();renderMetrics();renderDashboard();renderTasks();renderTimeline();renderDeliverables();renderFeedback();renderOwnerSelect();renderFeedbackTarget()}
function renderCounts(){document.querySelectorAll('[data-count="tasks"]').forEach(el=>el.textContent=state.tasks.filter(t=>t.status!=='Done').length);document.querySelectorAll('[data-count="approval"]').forEach(el=>el.textContent=state.deliverables.filter(d=>d.status==='Pending').length)}
function renderMetrics(){const total=state.tasks.length||1;const done=state.tasks.filter(t=>t.status==='Done').length;const active=state.tasks.filter(t=>t.status==='In Progress').length;const due=state.tasks.filter(t=>t.status!=='Done'&&daysUntil(t.due)>=0&&daysUntil(t.due)<=3).length;const approval=state.deliverables.filter(d=>d.status==='Pending').length;document.querySelector('[data-metric="progress"]').textContent=Math.round(done/total*100)+'%';document.querySelector('[data-metric="active"]').textContent=active;document.querySelector('[data-metric="due"]').textContent=due;document.querySelector('[data-metric="approval"]').textContent=approval}
function renderDashboard(){const tasks=state.tasks.filter(t=>t.status!=='Done').slice().sort((a,b)=>parseDate(a.due)-parseDate(b.due)).slice(0,5);document.querySelector('[data-dashboard-tasks]').innerHTML=tasks.map(t=>`<div class="task-row"><div class="task-main"><strong>${esc(t.name)}</strong><small>${esc(owner(t.owner)?.name||'미배정')} · ${formatDate(t.due)}</small></div><span class="priority ${t.priority}">${t.priority}</span><span class="status ${statusClass(t.status)}">${t.status}</span></div>`).join('')||'<p>진행 중인 업무가 없습니다.</p>';document.querySelector('[data-dashboard-milestones]').innerHTML=state.milestones.filter(m=>daysUntil(m.date)>=0).slice(0,3).map(m=>`<div class="milestone-item"><div><b>${esc(m.title)}</b><small>${esc(m.desc)}</small></div><time>${formatDate(m.date)}</time></div>`).join('');document.querySelector('[data-dashboard-deliverables]').innerHTML=state.deliverables.filter(d=>d.status==='Pending').map(d=>`<div class="approval-item"><div><b>${esc(d.name)}</b><small>${esc(d.version)} · ${esc(owner(d.owner)?.name||'')}</small></div><span class="status Pending">Pending</span></div>`).join('')||'<p>승인 대기 산출물이 없습니다.</p>'}
function renderTasks(){const tbody=document.querySelector('[data-tasks-table]');tbody.innerHTML=visibleTasks().map(t=>`<tr><td><div class="task-cell"><strong>${esc(t.name)}</strong><span>${t.id}</span></div></td><td>${esc(owner(t.owner)?.name||'미배정')}</td><td><span class="priority ${t.priority}">${t.priority}</span></td><td>${formatDate(t.due)}</td><td><span class="status ${statusClass(t.status)}">${t.status}</span></td><td><div class="action-group"><button class="tiny-button" data-status="${t.id}">상태</button><button class="tiny-button" data-owner="${t.id}">담당</button></div></td></tr>`).join('')||'<tr><td colspan="6">조건에 맞는 업무가 없습니다.</td></tr>';tbody.querySelectorAll('[data-status]').forEach(b=>b.addEventListener('click',()=>cycleTaskStatus(b.dataset.status)));tbody.querySelectorAll('[data-owner]').forEach(b=>b.addEventListener('click',()=>cycleOwner(b.dataset.owner)))}
function renderTimeline(){document.querySelector('[data-timeline]').innerHTML=state.milestones.map(m=>{const passed=daysUntil(m.date)<0;return `<article class="timeline-card"><time>${formatDate(m.date)}</time><div><h3>${esc(m.title)}</h3><p>${esc(m.desc)}</p></div><span class="status ${passed?'Done':'In-Progress'}">${passed?'Complete':'Upcoming'}</span></article>`}).join('')}
function renderDeliverables(){document.querySelector('[data-deliverables]').innerHTML=state.deliverables.map(d=>`<article class="deliverable-card"><h3>${esc(d.name)}</h3><p>${esc(owner(d.owner)?.name||'')} · ${esc(d.version)}</p><div class="deliverable-meta"><span>UPDATED ${formatDate(d.updated)}</span><span class="status ${d.status}">${d.status}</span></div><div class="deliverable-actions">${d.status==='Pending'?`<button class="primary-button" data-approve="${d.id}">승인</button>`:`<button class="secondary-button" data-reopen="${d.id}">재검토</button>`}<button class="secondary-button" data-feedback-deliverable="${d.id}">피드백</button></div></article>`).join('');document.querySelectorAll('[data-approve]').forEach(b=>b.addEventListener('click',()=>setDeliverable(b.dataset.approve,'Approved')));document.querySelectorAll('[data-reopen]').forEach(b=>b.addEventListener('click',()=>setDeliverable(b.dataset.reopen,'Pending')));document.querySelectorAll('[data-feedback-deliverable]').forEach(b=>b.addEventListener('click',()=>{setView('feedback');const select=document.querySelector('[data-feedback-target]');select.value=state.deliverables.find(d=>d.id===b.dataset.feedbackDeliverable)?.name||'';document.querySelector('[data-feedback-form] input')?.focus()}))}
function renderFeedback(){document.querySelector('[data-feedback-list]').innerHTML=state.feedback.slice().reverse().map(f=>`<article class="feedback-item"><strong>${esc(f.target)}</strong><p>${esc(f.message)}</p><small>${esc(f.author)} · ${esc(f.date)}</small></article>`).join('')||'<p>등록된 피드백이 없습니다.</p>'}
function renderOwnerSelect(){const select=document.querySelector('[data-owner-select]');if(select)select.innerHTML=owners.map(o=>`<option value="${o.id}">${esc(o.name)} · ${esc(o.role)}</option>`).join('')}
function renderFeedbackTarget(){const select=document.querySelector('[data-feedback-target]');if(select)select.innerHTML=state.deliverables.map(d=>`<option value="${esc(d.name)}">${esc(d.name)}</option>`).join('')}
function cycleTaskStatus(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;const order=['Todo','In Progress','Review','Done'];t.status=order[(order.indexOf(t.status)+1)%order.length];saveState();renderAll();toast(`업무 상태: ${t.status}`)}
function cycleOwner(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;const i=owners.findIndex(o=>o.id===t.owner);t.owner=owners[(i+1)%owners.length].id;saveState();renderAll();toast(`담당자: ${owner(t.owner).name}`)}
function setDeliverable(id,status){const d=state.deliverables.find(x=>x.id===id);if(!d)return;d.status=status;d.updated=new Date().toISOString().slice(0,10);saveState();renderAll();toast(status==='Approved'?'산출물을 승인했습니다.':'재검토 상태로 변경했습니다.')}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{currentFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('is-active',x===b));renderTasks()}));document.querySelector('[data-search]').addEventListener('input',e=>{searchQuery=e.target.value.trim();renderTasks()});
function openModal(){const m=document.querySelector('[data-modal="task"]');m.classList.add('is-open');m.setAttribute('aria-hidden','false');m.querySelector('input')?.focus()}function closeModal(){const m=document.querySelector('[data-modal="task"]');m.classList.remove('is-open');m.setAttribute('aria-hidden','true')}
document.querySelector('[data-open-task]').addEventListener('click',openModal);document.querySelector('[data-close]').addEventListener('click',closeModal);document.querySelector('[data-modal="task"]').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelector('[data-task-form]').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);state.tasks.unshift({id:'t'+Date.now().toString(36),name:fd.get('name').trim(),owner:fd.get('owner'),priority:fd.get('priority'),due:fd.get('due'),status:'Todo'});saveState();e.currentTarget.reset();closeModal();renderAll();setView('tasks');toast('새 업무를 추가했습니다.')});
document.querySelector('[data-feedback-form]').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);state.feedback.push({id:'f'+Date.now().toString(36),target:fd.get('target'),message:fd.get('message').trim(),author:'김도윤',date:new Date().toISOString().slice(0,10)});saveState();e.currentTarget.reset();renderAll();toast('피드백을 등록했습니다.')});
document.querySelector('[data-reset]').addEventListener('click',()=>{if(!confirm('Project Room 데모 데이터를 초기화할까요?'))return;state=cloneSeed();saveState();renderAll();toast('데모 데이터를 초기화했습니다.')});
const params=new URLSearchParams(location.search);const initial=params.get('view');renderAll();setView(['dashboard','tasks','timeline','deliverables','feedback'].includes(initial)?initial:'dashboard');
